CREATE TABLE IF NOT EXISTS users(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR (62) NOT NULL UNIQUE,
    first_name VARCHAR (46) NOT NULL,
    last_name VARCHAR (46) NOT NULL,
    password VARCHAR (255) NOT NULL,
    user_role VARCHAR (15) NOT NULL,
    user_status VARCHAR (15) NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS activate_key(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL,
    expiration_date TIMESTAMP NOT NULL,
    key VARCHAR (15) NOT NULL,
    user_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id)
        REFERENCES users (id));