version: '2'

services:
  uaa:
    image: '97musienko/uaa'
    ports:
    - 8080:8080
    depends_on:
      - db
      - url
    env_file:
      - service.env
  url:
    image: '97musienko/url'
    ports:
      - 8081:8081
    depends_on:
      - db
    env_file:
      - service.env
  db:
    image: 'postgres'
    env_file:
      - db.env



